package main

import ("fmt"
	"encoding/json"
	"crypto/tls"
        "github.com/parnurzeal/gorequest"
)
func main() {
   type biosStruct struct {
	RedfishSettings struct {
		OdataContext   string `json:"@odata.context"`
		OdataType      string `json:"@odata.type"`
		SettingsObject struct {
			OdataID string `json:"@odata.id"`
		} `json:"SettingsObject"`
	} `json:"@Redfish.Settings"`
	OdataContext string `json:"@odata.context"`
	OdataID      string `json:"@odata.id"`
	OdataType    string `json:"@odata.type"`
	Actions      struct {
		BiosChangePassword struct {
			Target string `json:"target"`
		} `json:"#Bios.ChangePassword"`
		BiosResetBios struct {
			Target string `json:"target"`
		} `json:"#Bios.ResetBios"`
	} `json:"Actions"`
	AttributeRegistry string `json:"AttributeRegistry"`
	Attributes        struct {
		AcPwrRcvry               string `json:"AcPwrRcvry"`
		AcPwrRcvryDelay          string `json:"AcPwrRcvryDelay"`
		AcPwrRcvryUserDelay      int    `json:"AcPwrRcvryUserDelay"`
		AesNi                    string `json:"AesNi"`
		AssetTag                 string `json:"AssetTag"`
		BootMode                 string `json:"BootMode"`
		BootSeqRetry             string `json:"BootSeqRetry"`
		CollaborativeCPUPerfCtrl string `json:"CollaborativeCpuPerfCtrl"`
		ConTermType              string `json:"ConTermType"`
		ControlledTurbo          string `json:"ControlledTurbo"`
		CorrEccSmi               string `json:"CorrEccSmi"`
		CurrentEmbVideoState     string `json:"CurrentEmbVideoState"`
		DcuIPPrefetcher          string `json:"DcuIpPrefetcher"`
		DcuStreamerPrefetcher    string `json:"DcuStreamerPrefetcher"`
		DynamicCoreAllocation    string `json:"DynamicCoreAllocation"`
		EmbSata                  string `json:"EmbSata"`
		EmbVideo                 string `json:"EmbVideo"`
		EnergyEfficientTurbo     string `json:"EnergyEfficientTurbo"`
		EnergyPerformanceBias    string `json:"EnergyPerformanceBias"`
		ErrPrompt                string `json:"ErrPrompt"`
		ExtSerialConnector       string `json:"ExtSerialConnector"`
		FailSafeBaud             string `json:"FailSafeBaud"`
		ForceInt10               string `json:"ForceInt10"`
		GlobalSlotDriverDisable  string `json:"GlobalSlotDriverDisable"`
		HddFailover              string `json:"HddFailover"`
		InSystemCharacterization string `json:"InSystemCharacterization"`
		IntegratedNetwork1       string `json:"IntegratedNetwork1"`
		IntegratedRaid           string `json:"IntegratedRaid"`
		IntelTxt                 string `json:"IntelTxt"`
		InternalUsb              string `json:"InternalUsb"`
		IoNonPostedPrefetch      string `json:"IoNonPostedPrefetch"`
		IoatEngine               string `json:"IoatEngine"`
		LogicalProc              string `json:"LogicalProc"`
		MemFrequency             string `json:"MemFrequency"`
		MemOpMode                string `json:"MemOpMode"`
		MemPatrolScrub           string `json:"MemPatrolScrub"`
		MemRefreshRate           string `json:"MemRefreshRate"`
		MemTest                  string `json:"MemTest"`
		MmioAbove4Gb             string `json:"MmioAbove4Gb"`
		MonitorMwait             string `json:"MonitorMwait"`
		NmiButton                string `json:"NmiButton"`
		NodeInterleave           string `json:"NodeInterleave"`
		NumLock                  string `json:"NumLock"`
		OneTimeBootMode          string `json:"OneTimeBootMode"`
		OneTimeBootSeqDev        string `json:"OneTimeBootSeqDev"`
		OneTimeHddSeqDev         string `json:"OneTimeHddSeqDev"`
		OsWatchdogTimer          string `json:"OsWatchdogTimer"`
		PasswordStatus           string `json:"PasswordStatus"`
		PowerSaver               string `json:"PowerSaver"`
		Proc1Brand               string `json:"Proc1Brand"`
		Proc1ID                  string `json:"Proc1Id"`
		Proc1L2Cache             string `json:"Proc1L2Cache"`
		Proc1L3Cache             string `json:"Proc1L3Cache"`
		Proc1Microcode           string `json:"Proc1Microcode"`
		Proc1NumCores            int    `json:"Proc1NumCores"`
		Proc1TurboCoreNum        string `json:"Proc1TurboCoreNum"`
		Proc2Brand               string `json:"Proc2Brand"`
		Proc2ID                  string `json:"Proc2Id"`
		Proc2L2Cache             string `json:"Proc2L2Cache"`
		Proc2L3Cache             string `json:"Proc2L3Cache"`
		Proc2Microcode           string `json:"Proc2Microcode"`
		Proc2NumCores            int    `json:"Proc2NumCores"`
		Proc2TurboCoreNum        string `json:"Proc2TurboCoreNum"`
		Proc64Bit                string `json:"Proc64bit"`
		ProcAdjCacheLine         string `json:"ProcAdjCacheLine"`
		ProcAts                  string `json:"ProcAts"`
		ProcBusSpeed             string `json:"ProcBusSpeed"`
		ProcC1E                  string `json:"ProcC1E"`
		ProcCStates              string `json:"ProcCStates"`
		ProcConfigTdp            string `json:"ProcConfigTdp"`
		ProcCoreSpeed            string `json:"ProcCoreSpeed"`
		ProcCores                string `json:"ProcCores"`
		ProcExecuteDisable       string `json:"ProcExecuteDisable"`
		ProcHwPrefetcher         string `json:"ProcHwPrefetcher"`
		ProcPwrPerf              string `json:"ProcPwrPerf"`
		ProcTurboMode            string `json:"ProcTurboMode"`
		ProcVirtualization       string `json:"ProcVirtualization"`
		ProcX2Apic               string `json:"ProcX2Apic"`
		PwrButton                string `json:"PwrButton"`
		QpiSpeed                 string `json:"QpiSpeed"`
		RedirAfterBoot           string `json:"RedirAfterBoot"`
		RtidSetting              string `json:"RtidSetting"`
		SHA256SetupPassword      string `json:"SHA256SetupPassword"`
		SHA256SetupPasswordSalt  string `json:"SHA256SetupPasswordSalt"`
		SHA256SystemPassword     string `json:"SHA256SystemPassword"`
		SHA256SystemPasswordSalt string `json:"SHA256SystemPasswordSalt"`
		SataPortA                string `json:"SataPortA"`
		SataPortACapacity        string `json:"SataPortACapacity"`
		SataPortADriveType       string `json:"SataPortADriveType"`
		SataPortAModel           string `json:"SataPortAModel"`
		SataPortB                string `json:"SataPortB"`
		SataPortBCapacity        string `json:"SataPortBCapacity"`
		SataPortBDriveType       string `json:"SataPortBDriveType"`
		SataPortBModel           string `json:"SataPortBModel"`
		SataPortC                string `json:"SataPortC"`
		SataPortCCapacity        string `json:"SataPortCCapacity"`
		SataPortCDriveType       string `json:"SataPortCDriveType"`
		SataPortCModel           string `json:"SataPortCModel"`
		SataPortD                string `json:"SataPortD"`
		SataPortDCapacity        string `json:"SataPortDCapacity"`
		SataPortDDriveType       string `json:"SataPortDDriveType"`
		SataPortDModel           string `json:"SataPortDModel"`
		SataPortE                string `json:"SataPortE"`
		SataPortECapacity        string `json:"SataPortECapacity"`
		SataPortEDriveType       string `json:"SataPortEDriveType"`
		SataPortEModel           string `json:"SataPortEModel"`
		SataPortF                string `json:"SataPortF"`
		SataPortFCapacity        string `json:"SataPortFCapacity"`
		SataPortFDriveType       string `json:"SataPortFDriveType"`
		SataPortFModel           string `json:"SataPortFModel"`
		SataPortG                string `json:"SataPortG"`
		SataPortGCapacity        string `json:"SataPortGCapacity"`
		SataPortGDriveType       string `json:"SataPortGDriveType"`
		SataPortGModel           string `json:"SataPortGModel"`
		SataPortH                string `json:"SataPortH"`
		SataPortHCapacity        string `json:"SataPortHCapacity"`
		SataPortHDriveType       string `json:"SataPortHDriveType"`
		SataPortHModel           string `json:"SataPortHModel"`
		SataPortI                string `json:"SataPortI"`
		SataPortICapacity        string `json:"SataPortICapacity"`
		SataPortIDriveType       string `json:"SataPortIDriveType"`
		SataPortIModel           string `json:"SataPortIModel"`
		SataPortJ                string `json:"SataPortJ"`
		SataPortJCapacity        string `json:"SataPortJCapacity"`
		SataPortJDriveType       string `json:"SataPortJDriveType"`
		SataPortJModel           string `json:"SataPortJModel"`
		SecureBoot               string `json:"SecureBoot"`
		SecureBootPolicy         string `json:"SecureBootPolicy"`
		SecurityFreezeLock       string `json:"SecurityFreezeLock"`
		SerialComm               string `json:"SerialComm"`
		SerialPortAddress        string `json:"SerialPortAddress"`
		SetBootOrderFqdd1        string `json:"SetBootOrderFqdd1"`
		SetBootOrderFqdd10       string `json:"SetBootOrderFqdd10"`
		SetBootOrderFqdd11       string `json:"SetBootOrderFqdd11"`
		SetBootOrderFqdd12       string `json:"SetBootOrderFqdd12"`
		SetBootOrderFqdd13       string `json:"SetBootOrderFqdd13"`
		SetBootOrderFqdd14       string `json:"SetBootOrderFqdd14"`
		SetBootOrderFqdd15       string `json:"SetBootOrderFqdd15"`
		SetBootOrderFqdd16       string `json:"SetBootOrderFqdd16"`
		SetBootOrderFqdd2        string `json:"SetBootOrderFqdd2"`
		SetBootOrderFqdd3        string `json:"SetBootOrderFqdd3"`
		SetBootOrderFqdd4        string `json:"SetBootOrderFqdd4"`
		SetBootOrderFqdd5        string `json:"SetBootOrderFqdd5"`
		SetBootOrderFqdd6        string `json:"SetBootOrderFqdd6"`
		SetBootOrderFqdd7        string `json:"SetBootOrderFqdd7"`
		SetBootOrderFqdd8        string `json:"SetBootOrderFqdd8"`
		SetBootOrderFqdd9        string `json:"SetBootOrderFqdd9"`
		SetLegacyHddOrderFqdd1   string `json:"SetLegacyHddOrderFqdd1"`
		SetLegacyHddOrderFqdd10  string `json:"SetLegacyHddOrderFqdd10"`
		SetLegacyHddOrderFqdd11  string `json:"SetLegacyHddOrderFqdd11"`
		SetLegacyHddOrderFqdd12  string `json:"SetLegacyHddOrderFqdd12"`
		SetLegacyHddOrderFqdd13  string `json:"SetLegacyHddOrderFqdd13"`
		SetLegacyHddOrderFqdd14  string `json:"SetLegacyHddOrderFqdd14"`
		SetLegacyHddOrderFqdd15  string `json:"SetLegacyHddOrderFqdd15"`
		SetLegacyHddOrderFqdd16  string `json:"SetLegacyHddOrderFqdd16"`
		SetLegacyHddOrderFqdd2   string `json:"SetLegacyHddOrderFqdd2"`
		SetLegacyHddOrderFqdd3   string `json:"SetLegacyHddOrderFqdd3"`
		SetLegacyHddOrderFqdd4   string `json:"SetLegacyHddOrderFqdd4"`
		SetLegacyHddOrderFqdd5   string `json:"SetLegacyHddOrderFqdd5"`
		SetLegacyHddOrderFqdd6   string `json:"SetLegacyHddOrderFqdd6"`
		SetLegacyHddOrderFqdd7   string `json:"SetLegacyHddOrderFqdd7"`
		SetLegacyHddOrderFqdd8   string `json:"SetLegacyHddOrderFqdd8"`
		SetLegacyHddOrderFqdd9   string `json:"SetLegacyHddOrderFqdd9"`
		SetupPassword            string `json:"SetupPassword"`
		Slot1                    string `json:"Slot1"`
		Slot1Bif                 string `json:"Slot1Bif"`
		Slot2                    string `json:"Slot2"`
		Slot2Bif                 string `json:"Slot2Bif"`
		Slot3                    string `json:"Slot3"`
		Slot3Bif                 string `json:"Slot3Bif"`
		SnoopHldOff              string `json:"SnoopHldOff"`
		SnoopMode                string `json:"SnoopMode"`
		SriovGlobalEnable        string `json:"SriovGlobalEnable"`
		SysMemSize               string `json:"SysMemSize"`
		SysMemSpeed              string `json:"SysMemSpeed"`
		SysMemType               string `json:"SysMemType"`
		SysMemVolt               string `json:"SysMemVolt"`
		SysMfrContactInfo        string `json:"SysMfrContactInfo"`
		SysPassword              string `json:"SysPassword"`
		SysProfile               string `json:"SysProfile"`
		SystemBiosVersion        string `json:"SystemBiosVersion"`
		SystemCpldVersion        string `json:"SystemCpldVersion"`
		SystemManufacturer       string `json:"SystemManufacturer"`
		SystemMeVersion          string `json:"SystemMeVersion"`
		SystemModelName          string `json:"SystemModelName"`
		SystemServiceTag         string `json:"SystemServiceTag"`
		TpmInfo                  string `json:"TpmInfo"`
		TpmStatus                string `json:"TpmStatus"`
		UefiComplianceVersion    string `json:"UefiComplianceVersion"`
		UefiVariableAccess       string `json:"UefiVariableAccess"`
		UncoreFrequency          string `json:"UncoreFrequency"`
		Usb3Setting              string `json:"Usb3Setting"`
		UsbPorts                 string `json:"UsbPorts"`
		VideoMem                 string `json:"VideoMem"`
		WorkloadProfile          string `json:"WorkloadProfile"`
		WriteCache               string `json:"WriteCache"`
		WriteDataCrc             string `json:"WriteDataCrc"`
	} `json:"Attributes"`
	Description string `json:"Description"`
	ID          string `json:"Id"`
	Name        string `json:"Name"`
}
   request := gorequest.New().TLSClientConfig(&tls.Config{ InsecureSkipVerify: true}).SetBasicAuth("root", "nfv1234")
   _, body, _ := request.Get("https://100.67.146.10/redfish/v1/Systems/System.Embedded.1/Bios").End()
   var b2 biosStruct
   json.Unmarshal([]byte(body), &b2)
   fmt.Println(b2.Attributes.BootMode)
}

